ARG UBUNTU_VERSION=24.04
# This needs to generally match the container host's environment.
ARG CUDA_VERSION=13.3.1
ARG CUDA_DOCKER_ARCH=sm_121

# Target the CUDA build image
ARG BASE_CUDA_DEV_CONTAINER=nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}

ARG BASE_CUDA_RUN_CONTAINER=nvidia/cuda:${CUDA_VERSION}-runtime-ubuntu${UBUNTU_VERSION}

FROM ${BASE_CUDA_DEV_CONTAINER} AS build
ARG CUDA_DOCKER_ARCH=sm_121


WORKDIR /app

COPY . .

RUN ln -s /usr/local/cuda-13.3/targets/sbsa-linux/lib/stubs/libcuda.so /usr/local/cuda-13.3/targets/sbsa-linux/lib/stubs/libcuda.so.1

ENV LD_LIBRARY_PATH=/usr/local/cuda-13.3/targets/sbsa-linux/lib/stubs:$LD_LIBRARY_PATH
ENV CUDA_ARCH=${CUDA_DOCKER_ARCH:-sm_121}
                
RUN make cuda-spark

FROM ${BASE_CUDA_RUN_CONTAINER} AS full

# curl need for healthcheck
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

WORKDIR /app


COPY --from=build /app/ds4 /app
COPY --from=build /app/ds4-* /app

