[unsloth/gemma-4-31B]
# 7 t/s generation - 350-450 t/s context parsing    
model = /models/huggingface/hub/models--unsloth--gemma-4-31B-it-GGUF/snapshots/965dd40a1c73d00a40f85a53bb540c1719d208ec/gemma-4-31B-it-UD-Q4_K_XL.gguf
ctx-size = 262144
temperature = 1.0
top-p = 0.95
top-k = 64
batch-size = 8192
ubatch-size = 2048
parallel = 1
flash-attn = true
cache-type-k = q8_0
cache-type-v = q8_0
kv-unified = true
mlock = true
threads = 20
threads-batch = 20

[Exil01/Qwen3.5-35B-1M]
model = /models/huggingface/hub/models--Exil01--Qwen3.5-35B-Uncensored-YaRN-1M/snapshots/905baef0417ac69c6cd67617ac777c4ab5443d94/Qwen3.5-35B-Uncensored-YaRN-1M-Q4_K_M.gguf
# multi modality encoder
mmproj = /models/huggingface/hub/models--Exil01--Qwen3.5-35B-Uncensored-YaRN-1M/snapshots/905baef0417ac69c6cd67617ac777c4ab5443d94/mmproj-uncensored-35b-f16.gguf
ctx-size = 1048576
rope-scaling = yarn
yarn-orig-ctx = 262144
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
context-shift = true
ctx-checkpoints = 8
n-gpu-layers = 99
batch-size = 8192
ubatch-size = 2048
parallel = 1
flash-attn = true
cache-type-k = q8_0
cache-type-v = q8_0
kv-unified = true
mlock = true
threads = 20
threads-batch = 20

[mradermacher/Nemotron-Cascade-2-30B]
# 60-70t/s generation - 2900t/s context parsing      
model = /models/huggingface/hub/models--mradermacher--Nemotron-Cascade-2-30B-A3B-i1-GGUF/snapshots/b685793198b3096b09c7d74ef9797e431c5be9f8/Nemotron-Cascade-2-30B-A3B.i1-Q4_K_M.gguf
ctx-size = 524288
n-predict = 32768
context-shift = true
ctx-checkpoints = 8
n-gpu-layers = 99
batch-size = 8192
ubatch-size = 2048
parallel = 2
flash-attn = true
cache-type-k = q8_0
cache-type-v = q8_0
kv-unified = true
mlock = true
threads = 20
threads-batch = 20
temp = 1.0
top-k = 40
top-p = 0.95
min-p = 0.05
presence-penalty = 0.0 

[unsloth/Qwen3.5-35B]
# 49-51t/s generation, 1800-2500t/s context parsing
# look https://unsloth.ai/docs/models/qwen3.5
model = /models/huggingface/hub/models--unsloth--Qwen3.5-35B-A3B-GGUF/snapshots/bc014a17be43adabd7066b7a86075ff935c6a4e2/Qwen3.5-35B-A3B-UD-Q4_K_XL.gguf
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
ctx-size = 524288
context-shift = true
ctx-checkpoints = 8
n-gpu-layers = 99
cache-ram = 16384
batch-size = 8192
ubatch-size = 8192
parallel = 2
flash-attn = true
# swa-full = false
cache-type-k = q8_0
cache-type-v = q8_0
kv-unified = true
mlock = true
threads = 20
threads-batch = 20

[noctrex/Qwen3.5-35B]
# 39-50 t/s generation, 1500-2000 t/s context parsing    
model = /models/huggingface/hub/models--noctrex--Qwen3.5-35B-A3B-MXFP4_MOE-GGUF/snapshots/f47863e4882e413c572e071d43dfc4d3962dae58/Qwen3.5-35B-A3B-MXFP4_MOE_BF16.gguf
# multi modality encoder
mmproj = /models/huggingface/hub/models--noctrex--Qwen3.5-35B-A3B-MXFP4_MOE-GGUF/snapshots/f47863e4882e413c572e071d43dfc4d3962dae58/mmproj-BF16.gguf
ctx-size = 524288
context-shift = true
ctx-checkpoints = 8
n-gpu-layers = 99
cache-ram = 16384
batch-size = 8192
ubatch-size = 8192
parallel = 2
flash-attn = true
# swa-full = false
cache-type-k = q8_0
cache-type-v = q8_0
kv-unified = true
mlock = true
threads = 20
threads-batch = 20
temp = 0.6
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 1.5


[unsloth/Qwen3.5-27B]
# 10t/s generation, 500t/s context parsing
# look https://unsloth.ai/docs/models/qwen3.5
model = /models/huggingface/hub/models--unsloth--Qwen3.5-27B-GGUF/snapshots/3221f178a6b842d04f1fb42f1c413534adcc0a6a/Qwen3.5-27B-UD-Q4_K_XL.gguf
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
ctx-size = 524288
context-shift = true
ctx-checkpoints = 8
n-gpu-layers = 99
# cache-ram = 16384
batch-size = 8192
ubatch-size = 4096
parallel = 2
flash-attn = true
# swa-full = false
cache-type-k = q8_0
cache-type-v = q8_0
kv-unified = true
mlock = true
threads = 20
threads-batch = 20


[noctrex/Qwen3-Next-80B]
model = /models/huggingface/hub/models--noctrex--Qwen3-Next-80B-A3B-Instruct-1M-MXFP4_MOE-GGUF/snapshots/4c791a92568d68271a1f38403b7932a518631787/Qwen3-Next-80B-A3B-Instruct-1M-MXFP4_MOE-00001-of-00003.gguf
ctx-size = 1048576
rope-scaling = yarn
rope-scale = 4
cache-ram = 16384
batch-size = 8192
ubatch-size = 4096

[unsloth/GLM-4.7-Flash-30B]
model = /models/huggingface/hub/models--unsloth--GLM-4.7-Flash-GGUF/snapshots/66205ea11ef638d83850389bd921e6c199f7504e/GLM-4.7-Flash-Q8_0.gguf
temp = 0.7
top-p = 1.0
min-p = 0.01
cache-ram = 16384
batch-size = 8192
ubatch-size = 4096

# outdated
# [Biomanticus/RYS-Qwen3.5-27B]
# 10 t/s generation - 400-500 t/s context parsing
# model = /models/huggingface/hub/models--Biomanticus--RYS-Qwen3.5-27B-gguf/snapshots/eb0e14f2d3c717f7692593ff3fddced66d56dba7/RYS-Qwen3.5-27B-Q4_K_M.gguf
# temp = 0.6
# top-p = 0.95
# top-k = 20
# min-p = 0.00
# ctx-size = 524288
# context-shift = true
# ctx-checkpoints = 8
# n-gpu-layers = 99
# batch-size = 8192
# ubatch-size = 4096
# parallel = 2
# flash-attn = true
# cache-type-k = q8_0
# cache-type-v = q8_0
# kv-unified = true
# mlock = true
# threads = 20
# threads-batch = 20

#[unsloth/Qwen3.5-120B]
# model = /models/huggingface/hub/models--unsloth--Qwen3.5-122B-A10B-GGUF/snapshots/d503adb1b5f3b29521713c7460735ed753b04e68/MXFP4_MOE/Qwen3.5-122B-A10B-MXFP4_MOE-00001-of-00003.gguf
# temp = 0.6
# top-p = 0.95
# top-k = 20
# min-p = 0.00
# ctx-size = 524288
# context-shift = true
# ctx-checkpoints = 8
# n-gpu-layers = 99
# cache-ram = 16384
# batch-size = 8192
# ubatch-size = 4096
# parallel = 2
# flash-attn = true
# cache-type-k = q8_0
# cache-type-v = q8_0
# kv-unified = true
# mlock = true
# threads = 20
# threads-batch = 20


# [Qwen/Qwen3-Coder-Next-80B-Q8]
# model = /models/huggingface/hub/models--Qwen--Qwen3-Coder-Next-GGUF/snapshots/b82fb7382639d97b38fa7672e526c760c2fb358e/Qwen3-Coder-Next-Q8_0/Qwen3-Coder-Next-Q8_0-00001-of-00004.gguf
# ctx-size = 262144
# cont-batching = true
# temp = 1.0
# top-p = 0.95
# top-k = 40
# cache-ram = 16384
# batch-size = 8192
# ubatch-size = 8192

# [rushyrush/MiniMax-M2.1-139B]
# model = /models/huggingface/hub/models--rushyrush-MiniMax-M2.1-REAP-139B-A10B-GGUF/snapshots/
# ctx-size = 167936


# don't feet im memory and bad russian
# [noctrex/MiniMax-M2.5-139B]
# model = /models/huggingface/hub/models--noctrex--MiniMax-M2.5-REAP-139B-A10B-MXFP4_MOE-GGUF/snapshots/6427bb42d0d3a4ee87070634815972cd99d281fd/MiniMax-M2.5-REAP-139B-A10B-MXFP4_MOE-00001-of-00004.gguf
# ctx-size = 196608
# ctx-checkpoints=16
# cache-reuse=2048
# batch-size=4096
# ubatch-size=1024
# parallel=2
# swa-full=true
# cont-batching=true

# stupid
# [cturan/IQuest-Coder-V1-40B]
# model = /models/huggingface/hub/models--cturan--IQuest-Coder-V1-40B-Instruct-GGUF/snapshots/c520c173b24f57d25e6431598cd2b3d2c4c8748e/IQuest-Coder-V1-40B-Instruct.Q4_K_M.gguf
# stupid
# [tiiuae/Falcon-H1R-7B]
# model = /models/huggingface/hub/models--tiiuae--Falcon-H1R-7B-GGUF/snapshots/21539e5e8334bfd5474da7fffd0f82d0a97c6d0e/Falcon-H1R-7B-Q8_0.gguf
# too stupid
# [noctrex/HyperNova-60B]
# model = /models/huggingface/hub/models--noctrex--HyperNova-60B-MXFP4_MOE-GGUF/snapshots/81f93ea3f69d38c89c8e032766573b5962185a73/HyperNova-60B-MXFP4_MOE.gguf
# too old
# [noctrex/Nemotron-3-Nano-30B]
# model = /models/huggingface/hub/models--noctrex--Nemotron-3-Nano-30B-A3B-MXFP4_MOE-GGUF/snapshots/175835a96514b1c3c12a5f4b842c829d26dba202/NVIDIA-Nemotron-3-Nano-30B-A3B-MXFP4_MOE.gguf
# too slow, but works
# [unsloth/Devstral-2-123B-Instruct-2512-GGUF]
# model = /models/huggingface/hub/models--unsloth--Devstral-2-123B-Instruct-2512-GGUF/snapshots/1f2bfbe35f7f9071d9b318374bf5eeffefab4459/UD-Q4_K_XL/Devstral-2-123B-Instruct-2512-UD-Q4_K_XL-00001-of-00002.gguf
# [bartowski/zai-org_GLM-4.7]
# model = /models/huggingface/hub/models--bartowski--zai-org_GLM-4.7-GGUF/snapshots/c47ba4573051e4a5146879669a8a95743b5302a4/zai-org_GLM-4.7-IQ1_M/zai-org_GLM-4.7-IQ1_M-00001-of-00003.gguf

# [endyjasmi/Qwen3-Embedding-8B]
# model = /models/huggingface/hub/models--endyjasmi--Qwen3-Embedding-8B-Q4_K_M-GGUF/snapshots/b74bf2a75d37d23867612c1b81655e4496535086/qwen3-embedding-8b-q4_k_m.gguf